import { openai } from "@ai-sdk/openai"
import { generateText } from "ai"

// Fallback questions for when API is unavailable
const fallbackQuestions = {
  spice: [
    "Is cereal actually soup?",
    "Pineapple on pizza is actually genius - change my mind",
    "Social media has made us lonelier, not more connected",
    "Tipping culture has gone too far",
    "Books will always be better than their movie adaptations",
    "Hot dogs are sandwiches and I'll die on this hill",
    "Influencers shouldn't be considered real celebrities",
    "We should normalize wearing pajamas in public",
    "Mint chocolate chip ice cream tastes like toothpaste",
    "The Oxford comma is completely unnecessary",
    "Cats are better pets than dogs",
    "Reality TV is destroying society",
    "Cryptocurrency is just modern-day gambling",
    "Working from home makes people less productive",
    "Superhero movies are overrated and formulaic",
    "Fast fashion should be illegal",
    "Participation trophies are ruining kids",
    "Streaming services have too many subscription fees",
    "Self-checkout machines are eliminating jobs unnecessarily",
    "Astrology is just as valid as psychology",
    "Video games cause violence in society",
    "Climate change is being exaggerated by the media",
    "Traditional marriage is an outdated concept",
    "College degrees are becoming worthless",
    "Artificial intelligence will replace most human jobs",
    "Veganism is just privileged virtue signaling",
    "Cancel culture is necessary for social progress",
    "Money can absolutely buy happiness",
    "Standardized testing should be abolished",
    "Social media age limits should be strictly enforced",
    "Remote work is killing company culture",
    "Gentrification is actually good for communities",
    "True crime podcasts glorify violence",
    "Plastic surgery should be more socially acceptable",
    "Dating apps have ruined modern romance",
    "Homework should be banned in elementary school",
    "Electric cars are just virtue signaling for the rich",
    "Influencer marketing is more effective than traditional ads",
    "Open relationships never actually work",
    "Minimum wage jobs aren't meant to be careers",
    "Social justice warriors do more harm than good",
    "Trigger warnings make people more sensitive",
    "Ghosting is an acceptable way to end relationships",
    "Parents should have licenses to raise children",
    "Zoos are just animal prisons",
    "Organic food is a marketing scam",
    "Dress codes are sexist and outdated",
    "Nepotism is worse than racism in Hollywood",
    "Meditation is just expensive sitting",
    "Sports are a waste of time and resources",
  ],
  chuckle: [
    "Would you rather fight 100 duck-sized horses or 1 horse-sized duck?",
    "If animals could talk, which species would be the rudest?",
    "What's the weirdest thing you've ever Googled at 3 AM?",
    "If you could only communicate through movie quotes, which movie would you choose?",
    "What would be the worst superpower to have?",
    "If your life had a theme song that played every time you entered a room, what would it be?",
    "What's the most useless talent you have?",
    "If you were a ghost, how would you haunt people?",
    "Would you rather have fingers as long as legs or legs as long as fingers?",
    "If you could replace all the grass in the world with something else, what would it be?",
    "What would be the worst thing to hear as you're going under anesthesia?",
    "If you had to wear a warning label, what would it say?",
    "Would you rather sweat mayo or have to sneeze but never be able to?",
    "If you could only eat foods that start with the first letter of your name, how screwed are you?",
    "What would be the creepiest thing you could say while passing a stranger on the street?",
    "If you were a vegetable, what vegetable would you be and why?",
    "Would you rather have a rewind button or a pause button for your life?",
    "If you could make any animal the size of an elephant, which would be the most terrifying?",
    "What's the weirdest thing you believed as a child?",
    "If you had to choose a cartoon character to be your roommate, who would it be?",
    "Would you rather always have to sing instead of speaking or dance everywhere you go?",
    "If you could add a 13th month to the year, what would you call it?",
    "What would be the worst name you could give a child?",
    "If you were arrested with no explanation, what would your friends assume you did?",
    "Would you rather have a head the size of a tennis ball or the size of a watermelon?",
    "If you could make one rule that everyone had to follow for a day, what would it be?",
    "What's the most ridiculous fact you know?",
    "If you had to live in a TV show for a month, which would you choose?",
    "Would you rather have taste buds in your stomach or be able to taste with your feet?",
    "If you could rename yourself, what name would you choose?",
    "What would be the worst thing to put in a piñata?",
    "If you had to eat the same meal every day for the rest of your life, what would it be?",
    "Would you rather have the ability to read minds but only negative thoughts, or never read minds again?",
    "If you could make any two animals fight, which would make the best match?",
    "What's the most embarrassing thing you've done in front of a crush?",
    "If you had to choose between never using the internet again or never watching TV/movies again, which would you pick?",
    "Would you rather have a permanent clown face or permanent clown voice?",
    "If you could only use one emoji for the rest of your life, which would it be?",
    "What would be your strategy in a zombie apocalypse?",
    "If you had to live without one of your five senses, which would you give up?",
    "Would you rather always have to hop everywhere or never be able to use stairs?",
    "If you could make any inanimate object sentient, what would cause the most chaos?",
    "What's the weirdest compliment you've ever received?",
    "If you had to choose a new name for Earth, what would it be?",
    "Would you rather have a dragon or be a dragon?",
    "If you could only speak in questions for a day, how would you order food?",
    "What would be the worst superpower to have during a job interview?",
    "If you had to choose between having no elbows or no knees, which would you pick?",
    "Would you rather have everything you draw become real or everything you say become true?",
    "If you could make any sound effect play every time you walked, what would it be?",
  ],
  drift: [
    "Do we choose who we become, or does life choose for us?",
    "What's a belief you held strongly that completely changed?",
    "If you could know the absolute truth about one thing, what would it be?",
    "What's the most beautiful thing about being human?",
    "Do you think we're living in the best or worst time in history?",
    "What would you tell your younger self if you could?",
    "Is there a difference between being alone and being lonely?",
    "What does it mean to live a meaningful life?",
    "If you could experience one emotion for the first time again, which would it be?",
    "What's something you've learned about yourself recently?",
    "Do you think people are fundamentally good or bad?",
    "What's a moment that changed your perspective on everything?",
    "If you could ask the universe one question and get a definitive answer, what would it be?",
    "What's something you wish you could unlearn?",
    "Do you believe in fate or do we create our own destiny?",
    "What's the most profound thing a stranger has ever said to you?",
    "If you could live in any time period, would you choose the past, present, or future?",
    "What's something you're still trying to figure out about yourself?",
    "Do you think consciousness continues after death?",
    "What's a question you're afraid to know the answer to?",
    "If you could feel what it's like to be someone else for a day, who would you choose?",
    "What's something you've always wanted to ask but never had the courage to?",
    "Do you think we're alone in the universe?",
    "What's the difference between existing and truly living?",
    "If you could change one thing about human nature, what would it be?",
    "What's something you've lost that you wish you could get back?",
    "Do you think love is a choice or something that happens to us?",
    "What's a truth about life that took you too long to learn?",
    "If you could see the world through anyone's eyes, whose would you choose?",
    "What's something you're grateful for that you never expected to be?",
    "Do you think we have free will or is everything predetermined?",
    "What's a memory you wish you could experience again for the first time?",
    "If you could understand the meaning behind one mystery of life, what would it be?",
    "What's something you've forgiven but never forgotten?",
    "Do you think suffering is necessary for growth?",
    "What's a realization that hit you like a ton of bricks?",
    "If you could have a conversation with your future self, what would you ask?",
    "What's something you've accepted about life that you used to fight against?",
    "Do you think we're meant to find our purpose or create it?",
    "What's a moment when you felt most connected to something bigger than yourself?",
    "If you could change one decision from your past, would you?",
    "What's something you understand now that you wish you understood earlier?",
    "Do you think happiness is a destination or a journey?",
    "What's a fear you've overcome that changed how you see the world?",
    "If you could give one piece of wisdom to humanity, what would it be?",
    "What's something you've learned from your biggest failure?",
    "Do you think we're born with our personality or do we develop it?",
    "What's a moment when you felt most authentically yourself?",
    "If you could relive one day of your life, which would it be and why?",
    "What's something you hope future generations will understand better than we do?",
  ],
  edge: [
    "Should pineapple be banned from pizza forever?",
    "Is it okay to lie to spare someone's feelings?",
    "Should social media require age verification?",
    "Is cancel culture helping or hurting society?",
    "Should we colonize Mars or fix Earth first?",
    "Is it ethical to eat meat in 2024?",
    "Should billionaires exist?",
    "Is privacy dead in the digital age?",
    "Should parents be allowed to genetically modify their unborn children?",
    "Is cultural appropriation always wrong?",
    "Should we bring back extinct species through cloning?",
    "Is it ethical to use AI to replace human workers?",
    "Should hate speech be protected under free speech?",
    "Is it wrong to have children in an overpopulated world?",
    "Should we allow people to sell their organs?",
    "Is it ethical to edit human genes to prevent disease?",
    "Should we tax people based on their carbon footprint?",
    "Is it wrong to judge people by their social media posts?",
    "Should we allow AI to make life-or-death medical decisions?",
    "Is it ethical to keep animals in captivity for entertainment?",
    "Should we have a universal basic income?",
    "Is it wrong to profit from life-saving medications?",
    "Should we allow designer babies?",
    "Is it ethical to use deepfake technology?",
    "Should we ban single-use plastics globally?",
    "Is it wrong to eat lab-grown meat?",
    "Should we allow people to choose their own death?",
    "Is it ethical to use animals for medical testing?",
    "Should we have mandatory voting?",
    "Is it wrong to discriminate based on genetic predispositions?",
    "Should we allow human cloning for medical purposes?",
    "Is it ethical to use surveillance to prevent crime?",
    "Should we ban fossil fuels immediately?",
    "Is it wrong to have more than two children?",
    "Should we allow people to buy citizenship?",
    "Is it ethical to use AI for military purposes?",
    "Should we have a maximum wage limit?",
    "Is it wrong to judge people by their appearance?",
    "Should we allow genetic enhancement for intelligence?",
    "Is it ethical to use prisoners for medical experiments?",
    "Should we ban all forms of gambling?",
    "Is it wrong to profit from natural disasters?",
    "Should we allow people to live forever if technology permits?",
    "Is it ethical to use AI to predict criminal behavior?",
    "Should we have mandatory organ donation?",
    "Is it wrong to eat insects if it's better for the environment?",
    "Should we allow people to edit their memories?",
    "Is it ethical to use technology to eliminate human emotions?",
    "Should we ban all forms of advertising to children?",
    "Is it wrong to have different laws for different religions?",
  ],
  glow: [
    "What compliment still sticks with you years later?",
    "What's the kindest thing a stranger has ever done for you?",
    "What small act of love do you do for yourself regularly?",
    "What's your favorite thing about your best friend?",
    "What's a simple pleasure that never gets old?",
    "What's the best advice you've ever received?",
    "What makes you feel most grateful?",
    "What's your favorite way to show someone you care?",
    "What's a memory that always makes you smile?",
    "What's something beautiful you noticed today?",
    "What's a tradition that brings you joy?",
    "What's the most thoughtful gift you've ever received?",
    "What's something you love about your hometown?",
    "What's a skill you're proud of developing?",
    "What's your favorite way to spend a quiet evening?",
    "What's something that always cheers you up when you're down?",
    "What's a moment when you felt truly proud of yourself?",
    "What's your favorite thing about the changing seasons?",
    "What's a book, movie, or song that changed your life?",
    "What's something you're looking forward to?",
    "What's your favorite childhood memory?",
    "What's something you appreciate about your family?",
    "What's a hobby that brings you peace?",
    "What's the most beautiful place you've ever been?",
    "What's something you love about your current age?",
    "What's a quality you admire in others?",
    "What's your favorite way to help others?",
    "What's something that makes you feel connected to nature?",
    "What's a moment when you felt completely content?",
    "What's your favorite thing to do on a rainy day?",
    "What's something you've learned to love about yourself?",
    "What's a small victory you celebrated recently?",
    "What's your favorite way to start the morning?",
    "What's something that always makes you laugh?",
    "What's a person who has positively influenced your life?",
    "What's your favorite thing about human kindness?",
    "What's a moment when you felt most loved?",
    "What's something you're grateful your parents taught you?",
    "What's your favorite way to celebrate good news?",
    "What's something that makes you feel hopeful about the future?",
    "What's a compliment you love giving to others?",
    "What's your favorite thing about friendship?",
    "What's a moment when you felt truly understood?",
    "What's something you love about your daily routine?",
    "What's your favorite way to treat yourself?",
    "What's a quality you hope to develop more of?",
    "What's something that makes you feel proud of humanity?",
    "What's your favorite thing about learning something new?",
    "What's a moment when you felt grateful to be alive?",
    "What's something you love about the people in your life?",
  ],
  flip: [], // Will be populated from other categories
}

// Populate flip category with random questions from all other categories
fallbackQuestions.flip = [
  ...fallbackQuestions.spice.slice(0, 10),
  ...fallbackQuestions.chuckle.slice(0, 10),
  ...fallbackQuestions.drift.slice(0, 10),
  ...fallbackQuestions.edge.slice(0, 10),
  ...fallbackQuestions.glow.slice(0, 10),
]

export async function POST(request: Request) {
  try {
    const { category } = await request.json()

    // Check if OpenAI API key is available
    const hasApiKey = process.env.OPENAI_API_KEY

    if (!hasApiKey) {
      // Use fallback questions when API key is missing
      const categoryQuestions = fallbackQuestions[category as keyof typeof fallbackQuestions] || fallbackQuestions.flip
      const randomQuestion = categoryQuestions[Math.floor(Math.random() * categoryQuestions.length)]

      return Response.json({
        question: randomQuestion,
        isAiGenerated: false,
      })
    }

    // Try to use OpenAI API
    const categoryPrompts = {
      spice: `Generate a spicy, controversial question that would spark debate. Think hot takes, unpopular opinions, or polarizing topics. Make it thought-provoking but not offensive. Examples: "Is cereal actually soup?" or "Social media has made us lonelier, not more connected". Return just the question, no quotes.`,

      chuckle: `Generate a funny, ridiculous question that would make people laugh and debate silly things. Think meme-worthy, absurd scenarios, or playful "would you rather" questions. Examples: "Would you rather fight 100 duck-sized horses or 1 horse-sized duck?" or "If animals could talk, which species would be the rudest?". Return just the question, no quotes.`,

      drift: `Generate a deep, philosophical question perfect for late-night conversations. Think existential, introspective, or meaningful topics that make people reflect on life. Examples: "Do we choose who we become, or does life choose for us?" or "What's the most beautiful thing about being human?". Return just the question, no quotes.`,

      edge: `Generate a bold, edgy question that pushes boundaries but stays respectful. Think controversial topics, moral dilemmas, or polarizing debates. Examples: "Should pineapple be banned from pizza forever?" or "Is it okay to lie to spare someone's feelings?". Return just the question, no quotes.`,

      glow: `Generate a wholesome, heartwarming question that brings out positive emotions and affirming thoughts. Think gratitude, kindness, self-love, or beautiful memories. Examples: "What compliment still sticks with you years later?" or "What's the kindest thing a stranger has ever done for you?". Return just the question, no quotes.`,

      flip: `Generate a random question that could fit any mood - funny, deep, controversial, wholesome, or silly. Mix up the vibe and surprise me! Return just the question, no quotes.`,
    }

    const prompt = categoryPrompts[category as keyof typeof categoryPrompts] || categoryPrompts.flip

    const { text } = await generateText({
      model: openai("gpt-4o"),
      prompt,
      maxTokens: 100,
    })

    return Response.json({
      question: text.trim(),
      isAiGenerated: true,
    })
  } catch (error) {
    console.error("Error generating question:", error)

    // Fallback to static questions on any error
    const { category } = await request.json()
    const categoryQuestions = fallbackQuestions[category as keyof typeof fallbackQuestions] || fallbackQuestions.flip
    const randomQuestion = categoryQuestions[Math.floor(Math.random() * categoryQuestions.length)]

    return Response.json({
      question: randomQuestion,
      isAiGenerated: false,
    })
  }
}
